### ISSUE TITLE
Slack link is incorrect

### ISSUE THREAD

**Issue by idvoretskyi** [containerd/containerd.io#34]
Containerd has a reference to https://slack.containerd.io/ on the CNCF website (https://www.cncf.io/projects/) and a shared invite to link https://dockercommunity.slack.com/ on the project's (https://containerd.io/) website.

https://slack.containerd.io/ is an accurate link.

**Comment by estesp** [comment]
I think we first have to decide where to push discussion and get all the maintainers on the same page. Is "slack.containerd.io" yet another Slack domain? It's not just a CNCF slack redirector?

Right now all the discussion is happening on Docker Community Slack in the channels #containerd and #containerd-dev (767 and 106 members in each channel respectively). We have discussed whether it makes sense to migrate to the CNCF Slack #containerd channel (178 members, but no discussion happens there yet). Does this PR link to yet-another-Slack? I'm not sure I'm even on slack.containerd.io 🙂

**Comment by mikebrow** [comment]
> I think we first have to decide where to push discussion and get all the maintainers on the same page. Is "slack.containerd.io" yet another Slack domain? It's not just a CNCF slack redirector?
> 
> Right now all the discussion is happening on Docker Community Slack in the channels #containerd and #containerd-dev (767 and 106 members in each channel respectively). We have discussed whether it makes sense to migrate to the CNCF Slack #containerd channel (178 members, but no discussion happens there yet). Does this PR link to yet-another-Slack? I'm not sure I'm even on slack.containerd.io 🙂

It's yet another slack domain, looks like it's funded by the linux foundation. I jumped on it to check this morning, it does not seem to be a redirector.

**Comment by dmcgowan** [comment]
We don't want to use a dedicated slack domain. If we can get `slack.containerd.io` to redirect to a slack that is used then we should that common redirect. 

Is there a way to delete that unused containerd slack to avoid confusion?

**Comment by idvoretskyi** [comment]
I'm fine with leaving this as-is once the containerd community will agree on the correct Slack space for discussions.

**Comment by AkihiroSuda** [comment]
What is the next step? Maybe we should open a ticket to CNCF support desk?

**Comment by wenhuizhang** [comment]
it redirects to CNCF
