### ISSUE TITLE
Update getting started documentation

### ISSUE THREAD

**Issue by dmcgowan** [containerd/containerd.io#78]
The getting started documentation is out of sync with the docs in the main repo. Additionally, how to get started with containerd likely does not reflect all the way in which users may be installing containerd.

**Comment by shannonxtreme** [comment]
What are the common ways to install containerd? https://github.com/containerd/containerd/blob/main/docs/cri/installation.md seems to have one method, and the existing docs content has another..

**Comment by estesp** [comment]
After #114 and #115 merge we can close this for now. The content will be as in-sync as possible for now.

**Comment by AkihiroSuda** [comment]
We have to cover deprecation of `cri-containerd-cni-*.*.*-linux-*.tar.gz`
https://github.com/containerd/containerd/blob/v1.6.2/RELEASES.md#deprecated-features
https://github.com/containerd/containerd/issues/6541

**Comment by AkihiroSuda** [comment]
We are going to replace https://containerd.io/docs/getting-started/ with https://github.com/containerd/containerd/blob/main/docs/getting-started.md
