### ISSUE TITLE
Downloads page incorrectly indicates 1.5 is still in beta

### ISSUE THREAD

**Issue by funkypenguin** [containerd/containerd.io#91]
Hey guys,

Heads up - I just noticed that https://containerd.io/downloads/ indicates that the latest 1.5 version is 1.5.0-beta4. However, the same page illustrates a wget command to install `1.5.0` (no beta), and `1.5.2` is already released, per https://github.com/containerd/containerd/releases

Cheers!
D

**Comment by estesp** [comment]
Updated in PR #92; seems the implementation of the downloads page was hitting GitHub pagination defaults, which I also fixed in the PR and in the preview, all releases are now shown.
