### ISSUE TITLE
move the doc from containerd/contaienrd to contaienrd/containerd.io

### ISSUE THREAD

**Issue by DawnGuoDev** [containerd/containerd.io#97]
Can I move the doc from containerd/contaienrd to contaienrd/containerd.io？I find some docs can be shared.

**Comment by AkihiroSuda** [comment]
Yes, appreciated.

This was also discussed in https://github.com/containerd/containerd.io/issues/80 but got stall

**Comment by kzys** [comment]
I actually want to have docs in containerd/containerd to keep them versioned, like https://www.envoyproxy.io/docs.

**Comment by AkihiroSuda** [comment]
Closing as a duplicate of #80
